# -*- Mode: makefile -*-
#
# Multiarch Tests - included from tests/tcg/Makefile.target
#
# These tests are plain C and built without any architecture specific code.
#

MULTIARCH_SRC=$(SRC_PATH)/tests/tcg/multiarch

# Set search path for all sources
VPATH 		+= $(MULTIARCH_SRC)
MULTIARCH_SRCS   =$(notdir $(wildcard $(MULTIARCH_SRC)/*.c))
MULTIARCH_TESTS  =$(MULTIARCH_SRCS:.c=)

# Update TESTS
TESTS		+=$(MULTIARCH_TESTS)

#
# The following are any additional rules needed to build things
#

testthread: LDFLAGS+=-lpthread

# Specialist Runners
run-test-mmap: test-mmap
	$(call quiet-command, $(QEMU) $< > test-mmap.out, "TEST", "$< (default) on $(TARGET_NAME)")
	$(call quiet-command, $(QEMU) -p 8192 $< 8192 > test-mmap-8192.out, "TEST", "$< (8k pages) on $(TARGET_NAME)")
	$(call quiet-command, $(QEMU) -p 16384 $< 16384 > test-mmap-16384.out, "TEST", "$< (16k pages) on $(TARGET_NAME)")
	$(call quiet-command, $(QEMU) -p 32768 $< 32768 > test-mmap-32768.out, "TEST", "$< (32k pages) on $(TARGET_NAME)")
