# -*- Mode: makefile -*-
#
# mipsel specific TCG tests
#
# Copyright (c) 2021 Philippe Mathieu-Daudé <f4bug@amsat.org>
#
# SPDX-License-Identifier: GPL-2.0-or-later

# 32-bit MSA is tested on big-endian target
