#!/bin/bash
#
# Non-NBD test cases for overriding BDRV_O_PROTOCOL by explicitly
# specifying a driver
#
# Copyright (C) 2015 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# creator
owner=mreitz@redhat.com

seq="$(basename $0)"
echo "QA output created by $seq"

here="$PWD"
status=1	# failure is the default!

_cleanup()
{
	_cleanup_test_img
}
trap "_cleanup; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_supported_fmt generic
_supported_proto file
_supported_os Linux

_make_test_img 64M

if test "$IMGOPTSSYNTAX" = "true"
then
    SYSEMU_DRIVE_ARG=id=drv,if=none,$TEST_IMG
    SYSEMU_EXTRA_ARGS=""
    IO_DRIVE_ARG="$TEST_IMG"
    IO_EXTRA_ARGS="--image-opts"
    if [ -n "$IMGKEYSECRET" ]; then
	SECRET_ARG="secret,id=keysec0,data=$IMGKEYSECRET"
	SYSEMU_EXTRA_ARGS="$SYSEMU_EXTRA_ARGS -object $SECRET_ARG"
	IO_EXTRA_ARGS="$IO_EXTRA_ARGS --object $SECRET_ARG"
    fi
else
    SYSEMU_DRIVE_ARG=id=drv,if=none,file="$TEST_IMG",driver=raw,file.driver=$IMGFMT
    SYSEMU_EXTRA_ARGS=""
    IO_DRIVE_ARG="json:{'driver': 'raw', 'file': {'driver': '$IMGFMT', 'file': {'filename': '$TEST_IMG'}}}"
    IO_EXTRA_ARGS=""
fi


echo "{'execute': 'qmp_capabilities'}
      {'execute': 'human-monitor-command',
       'arguments': {'command-line': 'qemu-io drv \"write -P 42 0 64k\"'}}
      {'execute': 'quit'}" \
    | $QEMU -qmp stdio -nographic -nodefaults $SYSEMU_EXTRA_ARGS \
            -drive $SYSEMU_DRIVE_ARG \
    | _filter_qmp | _filter_qemu_io
$QEMU_IO -c 'read -P 42 0 64k' "$TEST_IMG" | _filter_qemu_io

$QEMU_IO_PROG -c 'read -P 42 0 64k' \
    $IO_EXTRA_ARGS "$IO_DRIVE_ARG" \
    | _filter_qemu_io

# success, all done
echo
echo '*** done'
rm -f $seq.full
status=0
