#! /bin/bash
#
# qemu-img dd test

owner=fullmanet@gmail.com

seq="$(basename $0)"
echo "QA output created by $seq"

here="$PWD"
status=1

_cleanup()
{
    _cleanup_test_img
}
trap "_cleanup; exit \$status" 0 1 2 3 15

. ./common.rc
. ./common.filter
. ./common.pattern

_supported_fmt generic
_supported_proto file
_supported_os Linux

echo
echo "== Creating image =="

size=1M
_make_test_img $size
_check_test_img

$QEMU_IO -c "write -P 0xa 0 $size" "$TEST_IMG" | _filter_qemu_io

echo
echo "== Converting the image with dd =="

$QEMU_IMG dd if="$TEST_IMG" of="$TEST_IMG.out" -O "$IMGFMT"
$QEMU_IMG check "$TEST_IMG.out" -f "$IMGFMT" 2>&1  | _filter_testdir | \
    sed -e '/allocated.*fragmented.*compressed clusters/d' \
        -e 's/qemu-img: This image format does not support checks/No errors were found on the image./' \
        -e '/Image end offset: [0-9]\+/d'

echo
echo "== Compare the images with qemu-img compare =="

$QEMU_IMG compare "$TEST_IMG" "$TEST_IMG.out"

echo
echo "*** done"
rm -f "$seq.full"
status=0
