#!/usr/bin/env bash
#
# Test that encryption key managment erases the key material
# in addition to the header
# Based on 134
#
# Copyright (C) 2019 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# creator
owner=mlevitsk@redhat.com

seq=`basename $0`
echo "QA output created by $seq"

status=1	# failure is the default!

_cleanup()
{
	_cleanup_test_img
}
trap "_cleanup; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_supported_fmt luks
_supported_proto file #TODO

QEMU_IO_OPTIONS=$QEMU_IO_OPTIONS_NO_FMT

# you are supposed to see the password as *******, see :-)
SECRET0="--object secret,id=sec0,data=hunter0"
SECRET1="--object secret,id=sec1,data=hunter1"
SECRETS="$SECRET0 $SECRET1"


IMGSPEC0="driver=$IMGFMT,file.filename=$TEST_IMG,key-secret=sec0"
IMGSPEC1="driver=$IMGFMT,file.filename=$TEST_IMG,key-secret=sec1"

echo "== creating a test image =="
_make_test_img $SECRET0 -o "key-secret=sec0,iter-time=10"   32M

echo
echo "== test that key 0 opens the image =="
$QEMU_IO $SECRET0 -c "read 0 4096" --image-opts $IMGSPEC0 | _filter_qemu_io | _filter_testdir

echo
echo "== adding a password to slot 1 =="
$QEMU_IMG add_encryption_key $SECRETS --image-opts $IMGSPEC0 --keydef key-secret=sec1,slot=1,iter-time=10

echo
echo "== 'backup' the image header =="
dd if=$TEST_IMG_FILE of=${TEST_IMG_FILE}.bk bs=4K skip=0 count=1

echo
echo "== erase slot 0 =="
$QEMU_IMG erase_encryption_key $SECRETS --image-opts $IMGSPEC1 --keydef slot=0 | _filter_img_create

echo
echo "== test that key 0 doesn't open the image =="
$QEMU_IO $SECRET0 -c "read 0 4096" --image-opts $IMGSPEC0 | _filter_qemu_io | _filter_testdir

echo
echo "== 'restore' the image header =="
dd if=${TEST_IMG_FILE}.bk of=${TEST_IMG_FILE} bs=4K skip=0 count=1 conv=notrunc

echo
echo "== test that key 0 still doesn't open the image (key material is erased) =="
$QEMU_IO $SECRETS -c "read 0 4096" --image-opts $IMGSPEC0 | _filter_qemu_io | _filter_testdir

echo
echo "== test that key 1 still works =="
$QEMU_IO $SECRETS -c "read 0 4096" --image-opts $IMGSPEC1 | _filter_qemu_io | _filter_testdir

echo "*** done"
rm -f $seq.full
status=0


exit 0
