#!/usr/bin/env python3
# group: meta
#
# Copyright (C) 2020 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import shutil
import sys

import iotests
import linters


# Looking for the list of files to exclude from linting? See linters.py.


def main() -> None:
    for linter in ('pylint-3', 'mypy'):
        if shutil.which(linter) is None:
            iotests.notrun(f'{linter} not found')

    files = linters.get_test_files()

    iotests.logger.debug('Files to be checked:')
    iotests.logger.debug(', '.join(sorted(files)))

    env = os.environ.copy()
    env['MYPYPATH'] = env['PYTHONPATH']

    print('=== pylint ===')
    sys.stdout.flush()
    linters.run_linter('pylint', files, env=env)

    print('=== mypy ===')
    sys.stdout.flush()
    linters.run_linter('mypy', files, env=env, suppress_output=True)


iotests.script_main(main)
