#!/usr/bin/env python3
#
# Copyright (C) 2020 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.



# Regression test for avoiding an assertion when the 'backing file'
# parameter (-b) is set to an empty string for qemu-img create
#
#   qemu-img create -f qcow2 -b '' /tmp/foo
#
# This ensures the invalid parameter is handled with a user-
# friendly message instead of a failed assertion.

import iotests

class TestEmptyBackingFilename(iotests.QMPTestCase):


    def test_empty_backing_file_name(self):
        actual = iotests.qemu_img_pipe(
                'create',
                '-f', 'qcow2',
                '-b', '',
                '/tmp/foo'
        )
        expected = 'qemu-img: /tmp/foo: Expected backing file name,' \
                   ' got empty string'

        self.assertEqual(actual.strip(), expected.strip())


if __name__ == '__main__':
    iotests.main(supported_fmts=['raw', 'qcow2'])
