#!/bin/bash

# Fake crm_master for COLO testing
#
# Copyright (c) Lukas Straub <lukasstraub2@web.de>
#
# This work is licensed under the terms of the GNU GPL, version 2 or
# later.  See the COPYING file in the top-level directory.

TMPDIR="$HA_RSCTMP"
score=0
query=0

OPTIND=1
while getopts 'Qql:Dv:N:G' opt; do
    case "$opt" in
        Q|q)
            # Noop
        ;;
        "l")
            # Noop
        ;;
        "D")
            score=0
        ;;
        "v")
            score=$OPTARG
        ;;
        "N")
            TMPDIR="$COLO_TEST_REMOTE_TMP"
        ;;
        "G")
            query=1
        ;;
    esac
done

if (( query )); then
    cat "${TMPDIR}/master_score" || exit 1
else
    echo $score > "${TMPDIR}/master_score" || exit 1
fi

exit 0
