#!/bin/bash -e
#
# Run block test cases
#
# Copyright (c) 2017 Red Hat Inc.
#
# Authors:
#  Fam Zheng <famz@redhat.com>
#
# This work is licensed under the terms of the GNU GPL, version 2
# or (at your option) any later version. See the COPYING file in
# the top-level directory.

. common.rc

cd "$BUILD_DIR"

build_qemu --target-list=x86_64-softmmu
cd tests/qemu-iotests
./check -raw
./check -qcow2
