# -*- Mode: makefile -*-
#
# x86_64 tests - included from tests/tcg/Makefile.target
#
# Currently we only build test-x86_64 and test-i386-ssse3 from
# $(SRC_PATH)/tests/tcg/i386/
#

include $(SRC_PATH)/tests/tcg/i386/Makefile.target

X86_64_TESTS += test-2413

ifeq ($(filter %-linux-user, $(TARGET)),$(TARGET))
X86_64_TESTS += vsyscall
X86_64_TESTS += noexec
X86_64_TESTS += cmpxchg
X86_64_TESTS += adox
X86_64_TESTS += test-1648
PLUGINS_TESTS += test-plugin-mem-access
TESTS=$(MULTIARCH_TESTS) $(X86_64_TESTS) test-x86_64
else
TESTS=$(MULTIARCH_TESTS)
endif

adox: CFLAGS=-O2

run-test-i386-ssse3: QEMU_OPTS += -cpu max
run-plugin-test-i386-ssse3-%: QEMU_OPTS += -cpu max

run-plugin-test-plugin-mem-access-with-libmem.so: \
	PLUGIN_ARGS=$(COMMA)print-accesses=true
run-plugin-test-plugin-mem-access-with-libmem.so: \
	CHECK_PLUGIN_OUTPUT_COMMAND= \
	$(SRC_PATH)/tests/tcg/x86_64/check-plugin-mem-access.sh

test-x86_64: LDFLAGS+=-lm -lc
test-x86_64: test-i386.c test-i386.h test-i386-shift.h test-i386-muldiv.h
	$(CC) $(CFLAGS) $< -o $@ $(LDFLAGS)

%: $(SRC_PATH)/tests/tcg/x86_64/%.c
	$(CC) $(CFLAGS) $< -o $@ $(LDFLAGS)
