CROSS_CC ?= loongarch64-linux-gnu-gcc

all: vdso.so

vdso.so: vdso.S vdso.ld vdso-asmoffset.h Makefile.vdso
	$(CROSS_CC) -nostdlib -fpic -shared -Wl,-T,vdso.ld -Wl,--build-id=sha1 \
	   -Wl,-h,linux-vdso.so.1 -Wl,--hash-style=both vdso.S -o $@
