VPATH+=$(SRC_PATH)/tests/tcg/s390x
CFLAGS+=-march=zEC12 -m64
TESTS+=hello-s390x
TESTS+=csst
TESTS+=ipm
TESTS+=exrl-trt
TESTS+=exrl-trtr
TESTS+=pack

VECTOR_TESTS=vge
TESTS+=$(VECTOR_TESTS)

#enable vectors and optimisation for vector tests
$(VECTOR_TESTS): CFLAGS+=-march=z13 -O2
