# -*- Mode: makefile -*-
#
# s390x specific tweaks - specifically masking out broken tests

run-linux-test: linux-test
	$(call quiet-command, /bin/true, "BROKEN TEST", "$< SKIPPED on $(TARGET_NAME)")
