S390X_SRC=$(SRC_PATH)/tests/tcg/s390x
VPATH+=$(S390X_SRC)
QEMU_OPTS=-action panic=exit-failure -kernel

%: %.S
	$(CC) -march=z13 -m64 -nostdlib -static -Wl,-Ttext=0 \
		-Wl,--build-id=none -D__ASSEMBLY__ -DCONFIG_SOFTMMU $< -o $@

TESTS += unaligned-lowcore
TESTS += bal
TESTS += sam

include $(S390X_SRC)/pgm-specification.mak
