# -*- Mode: makefile -*-
#
# AArch64 specific tweaks

AARCH64_SRC=$(SRC_PATH)/tests/tcg/aarch64
VPATH 		+= $(AARCH64_SRC)

# we don't build any of the ARM tests
AARCH64_TESTS=$(filter-out $(ARM_TESTS), $(TESTS))
AARCH64_TESTS+=fcvt sysregs
TESTS:=$(AARCH64_TESTS)

fcvt: LDFLAGS+=-lm
