# Default configuration for m68k-softmmu

CONFIG_COLDFIRE=y
CONFIG_PTIMER=y
CONFIG_ESCC=y
CONFIG_FRAMEBUFFER=y
CONFIG_ADB=y
CONFIG_MOS6522=y
CONFIG_MAC_VIA=y
CONFIG_Q800_IRQ=y
CONFIG_MAC=y
CONFIG_SCSI=y
CONFIG_ESP=y
CONFIG_ASC=y
CONFIG_MACFB=y
CONFIG_NUBUS=y
CONFIG_DP8393X=y
CONFIG_SWIM=y
