[package]
name = "migration"
version = "0.1.0"
description = "Rust bindings for QEMU/migration"
resolver = "2"
publish = false

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
common = { path = "../common" }
util = { path = "../util" }

[lints]
workspace = true
