#!/usr/bin/env python3
#
# Test blockdev-add transaction action
#
# Copyright (c) 2022 Virtuozzo International GmbH.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import iotests
from iotests import log

iotests.script_initialize(supported_fmts=['qcow2'])

with iotests.VM() as vm:
    vm.launch()

    # Use same node-name for nodes, neither one should appear.
    vm.qmp_log('transaction', actions=[
        {'type': 'blockdev-add',
         'data': {'node-name': 'node0', 'driver': 'null-co',
                  'size': 1024 * 1024}},
        {'type': 'blockdev-add',
         'data': {'node-name': 'node0', 'driver': 'null-co',
                  'size': 1024 * 1024}}
    ])

    n = len(vm.qmp('query-named-block-nodes')['return'])
    log(f'Created {n} nodes')

    vm.qmp_log('transaction', actions=[
        {'type': 'blockdev-add',
         'data': {'node-name': 'node0', 'driver': 'null-co',
                  'size': 1024 * 1024}},
        {'type': 'blockdev-add',
         'data': {'node-name': 'node1', 'driver': 'null-co',
                  'size': 1024 * 1024}}
    ])

    n = len(vm.qmp('query-named-block-nodes')['return'])
    log(f'Created {n} nodes')
