#!/usr/bin/env bash
# group: rw auto quick
#
# Test blockdev-mirror with raw sparse destination
#
# Copyright (C) 2025 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

seq="$(basename $0)"
echo "QA output created by $seq"

status=1 # failure is the default!

_cleanup()
{
    _cleanup_test_img
    _cleanup_qemu
}
trap "_cleanup; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
cd ..
. ./common.rc
. ./common.filter
. ./common.qemu

_supported_fmt qcow2 raw  # Format of the source. dst is always raw file
_supported_proto file
_supported_os Linux

echo
echo "=== Initial image setup ==="
echo

TEST_IMG="$TEST_IMG.base" _make_test_img 20M
$QEMU_IO -c 'w 8M 2M' -f $IMGFMT "$TEST_IMG.base" | _filter_qemu_io

_launch_qemu -machine q35 \
    -blockdev '{"driver":"file", "cache":{"direct":true, "no-flush":false},
                "filename":"'"$TEST_IMG.base"'", "node-name":"src-file"}' \
    -blockdev '{"driver":"'$IMGFMT'", "node-name":"src", "file":"src-file"}'
h1=$QEMU_HANDLE
_send_qemu_cmd $h1 '{"execute": "qmp_capabilities"}' 'return'

# Each of these combinations should result in a sparse destination;
# the destination should only be fully allocated if pre-allocated
for creation in external blockdev-create; do
for discard in ignore unmap; do

echo
echo "=== Destination with $creation creation and discard=$discard ==="
echo

rm -f $TEST_IMG
if test $creation = external; then
    truncate --size=20M $TEST_IMG
else
    _send_qemu_cmd $h1 '{"execute": "blockdev-create", "arguments":
          {"options": {"driver":"file", "filename":"'$TEST_IMG'",
          "size":'$((20*1024*1024))'}, "job-id":"job1"}}' 'concluded'
    _send_qemu_cmd $h1 '{"execute": "job-dismiss", "arguments":
          {"id": "job1"}}' 'return'
fi
_send_qemu_cmd $h1 '{"execute": "blockdev-add", "arguments":
                     {"node-name": "dst", "driver":"file",
                      "filename":"'$TEST_IMG'", "aio":"threads",
                      "auto-read-only":true, "discard":"'$discard'"}}' 'return'
_send_qemu_cmd $h1 '{"execute":"blockdev-mirror", "arguments":
                     {"sync":"full", "device":"src", "target":"dst",
                      "job-id":"job2"}}' 'return'
_timed_wait_for $h1 '"ready"'
_send_qemu_cmd $h1 '{"execute": "job-complete", "arguments":
               {"id":"job2"}}' 'return'
_send_qemu_cmd $h1 '{"execute": "blockdev-del", "arguments":
                {"node-name": "dst"}}' 'return'
$QEMU_IMG compare -f $IMGFMT -F raw $TEST_IMG.base $TEST_IMG
$QEMU_IMG info -f raw $TEST_IMG | grep '^disk size:'

done
done

_send_qemu_cmd $h1 '{"execute":"quit"}' ''

# success, all done
echo '*** done'
rm -f $seq.full
status=0
