brace_style = "AlwaysNextLine"
comment_width = 80
edition = "2021"
group_imports = "StdExternalCrate"
imports_granularity = "item"
max_width = 80
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
