# -*- Mode: makefile -*-
#
# sparc specific tweaks and masking out broken tests

# different from the other hangs:
# tests/tcg/multiarch/linux-test.c:264: Value too large for defined data type (ret=-1, errno=92/Value too large for defined data type)
run-linux-test: linux-test
	$(call skip-test, $<, "BROKEN")

# currently broken: hangs after the first thread exits
run-signals: signals
	$(call skip-test, $<, "BROKEN")

run-plugin-signals-with-%: signals
	$(call skip-test, $<, "BROKEN")

# On Sparc64 Linux support 8k pages
EXTRA_RUNS+=run-test-mmap-8192
