/*
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef QEMU_PASSTHROUGH_PROTOCOL_H
#define QEMU_PASSTHROUGH_PROTOCOL_H

#define PASSTHROUGH_MAGIC_SYSCALL 4096
#define PASSTHROUGH_OP_LOAD_HTL 1
#define PASSTHROUGH_OP_DLSYM 2
#define PASSTHROUGH_OP_INVOKE 3
#define PASSTHROUGH_OP_CLOSE_HTL 4

#endif /* QEMU_PASSTHROUGH_PROTOCOL_H */
