ifeq ($(CONFIG_VIRTIO)$(CONFIG_VIRTFS)$(CONFIG_PCI),yyy)
# Lots of the fsdev/9pcode is pulled in by vl.c via qemu_fsdev_add.
# only pull in the actual virtio-9p device if we also enabled virtio.
common-obj-y = qemu-fsdev.o 9p-marshal.o 9p-iov-marshal.o
endif
common-obj-y += qemu-fsdev-opts.o qemu-fsdev-throttle.o
