# This work is licensed under the terms of the GNU GPL, version 2.
# See the COPYING file in the top-level directory.
"""
QAPI Rust generator
"""

import os
import re
import subprocess
import sys

from .common import mcgen as mcgen_common
from .gen import QAPIGen
from .schema import QAPISchemaVisitor


def mcgen(s: str, **kwds: object) -> str:
    s = mcgen_common(s, **kwds)
    return re.sub(r'(?: *\n)+', '\n', s)


class QAPIGenRs(QAPIGen):
    def __init__(self, fname: str, blurb: str, pydoc: str):
        super().__init__(fname)
        self._blurb = blurb
        self._copyright = '\n//! '.join(re.findall(r'^Copyright .*', pydoc,
                                                   re.MULTILINE))

    def _top(self) -> str:
        return mcgen('''
// @generated by qapi-gen, DO NOT EDIT

//!
//! Schema-defined QAPI types
//!
//! %(copyright)s
//!
//! This work is licensed under the terms of the GNU LGPL, version 2.1 or
//! later. See the COPYING.LIB file in the top-level directory.

''',
                     tool=os.path.basename(sys.argv[0]),
                     blurb=self._blurb, copyright=self._copyright)


class QAPISchemaRsVisitor(QAPISchemaVisitor):

    def __init__(self, prefix: str, what: str,
                 blurb: str, pydoc: str):
        super().__init__()
        self._prefix = prefix
        self._what = what
        self._gen = QAPIGenRs(self._prefix + self._what + '.rs', blurb, pydoc)

    def write(self, output_dir: str) -> None:
        self._gen.write(output_dir)

        try:
            subprocess.check_call(['rustfmt', self._gen.fname], cwd=output_dir)
        except FileNotFoundError:
            pass
