"""
QAPI Rust sys/ffi generator
"""

from qapi.common import *
from qapi.schema import QAPISchemaEnumMember, QAPISchemaObjectType
from qapi.rs import QAPISchemaRsVisitor, rs_systype, rs_name


objects_seen = set()


def gen_rs_sys_enum(name, members, prefix=None):
    # append automatically generated _max value
    enum_members = members + [QAPISchemaEnumMember('_MAX', None)]

    ret = mcgen('''

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "dbus", derive(Deserialize_repr, Serialize_repr, Type))]
#[repr(i32)] // FIXME: serde-repr#10
pub enum %(rs_name)s {
''',
    rs_name=rs_name(name))

    for m in enum_members:
        ret += mcgen('''
    %(c_enum)s,
''',
                     c_enum=to_camel_case(rs_name(m.name, False)))
    ret += mcgen('''
}
''')
    return ret


def gen_rs_sys_struct_members(members):
    ret = ''
    for memb in members:
        if memb.optional:
            ret += mcgen('''
    pub has_%(rs_name)s: bool,
''',
                         rs_name=rs_name(memb.name))
        ret += mcgen('''
    pub %(rs_name)s: %(rs_systype)s,
''',
                     rs_systype=rs_systype(memb.type.c_type(), ''), rs_name=rs_name(memb.name))
    return ret


def gen_rs_sys_free(ty):
    return mcgen('''

extern "C" {
    pub fn qapi_free_%(ty)s(obj: *mut %(ty)s);
}
''', ty=ty)


def gen_rs_sys_object(name, ifcond, base, members, variants):
    if name in objects_seen:
        return ''

    ret = ''
    objects_seen.add(name)
    if variants:
        ret += 'variants TODO'

    ret += gen_rs_sys_free(rs_name(name))
    ret += mcgen('''

#[repr(C)]
#[derive(Debug)]
pub struct %(rs_name)s {
''',
                 rs_name=rs_name(name))

    if base:
        ret += 'Base TODO'

    ret += gen_rs_sys_struct_members(members)

    ret += mcgen('''
}
''')
    return ret


def gen_rs_sys_variant(name, ifcond, variants):
    if name in objects_seen:
        return ''

    objects_seen.add(name)

    vs = ''
    for var in variants.variants:
        if var.type.name == 'q_empty':
            continue
        vs += mcgen('''
    pub %(mem_name)s: %(rs_systype)s,
''',
                     rs_systype=rs_systype(var.type.c_unboxed_type(), ''),
                     mem_name=rs_name(var.name))

    return mcgen('''

#[repr(C)]
pub union %(rs_name)sUnion {
    %(variants)s
}

#[repr(C)]
pub struct %(rs_name)s {
    pub ty: QType,
    pub u: %(rs_name)sUnion,
}
''',
                 rs_name=rs_name(name), variants=vs)


def gen_rs_sys_array(name, element_type):
    ret = mcgen('''

#[repr(C)]
pub struct %(rs_name)s {
    pub next: *mut %(rs_name)s,
    pub value: %(rs_systype)s,
}

impl ::std::fmt::Debug for %(rs_name)s {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("%(rs_name)s @ {:?}", self as *const _))
            .finish()
    }
}
''',
                 rs_name=rs_name(name), rs_systype=rs_systype(element_type.c_type(), ''))
    ret += gen_rs_sys_free(rs_name(name))
    return ret


class QAPISchemaGenRsSysTypeVisitor(QAPISchemaRsVisitor):

    def __init__(self, prefix):
        super().__init__(prefix, 'qapi-sys-types')

    def visit_begin(self, schema):
        # gen_object() is recursive, ensure it doesn't visit the empty type
        objects_seen.add(schema.the_empty_object_type.name)
        self._gen.preamble_add(
            mcgen('''
// generated by qapi-gen, DO NOT EDIT

#[cfg(feature = "dbus")]
use serde_repr::{Deserialize_repr, Serialize_repr};
#[cfg(feature = "dbus")]
use zvariant_derive::Type;

use crate::qemu_sys::{QNull, QObject};

'''))

    def visit_enum_type(self, name, info, ifcond, features, members, prefix):
        self._gen.add(gen_rs_sys_enum(name, members, prefix))

    def visit_array_type(self, name, info, ifcond, element_type):
        self._gen.add(gen_rs_sys_array(name, element_type))

    def visit_object_type(self, name, info, ifcond, features,
                          base, members, variants):
        if name.startswith('q_'):
            return
        self._gen.add(gen_rs_sys_object(name, ifcond, base, members, variants))

    def visit_alternate_type(self, name, info, ifcond, features, variants):
        self._gen.add(gen_rs_sys_variant(name, ifcond, variants))


def gen_rs_systypes(schema, output_dir, prefix, opt_builtins):
    vis = QAPISchemaGenRsSysTypeVisitor(prefix)
    schema.visit(vis)
    vis.write(output_dir)
