#!/usr/bin/env python3

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..', 'python'))
from qemu.aqmp import qmp_send


if __name__ == '__main__':
    qmp_send.main()
