common-obj-y += virtio-rng.o
common-obj-$(CONFIG_VIRTIO_PCI) += virtio-pci.o
common-obj-y += virtio-bus.o
common-obj-y += virtio-mmio.o
trace-obj-y += trace.o
trace-obj-$(CONFIG_TRACE_DTRACE) += trace-dtrace.o

obj-y += virtio.o virtio-balloon.o 
obj-$(CONFIG_LINUX) += vhost.o vhost-backend.o vhost-user.o

obj-$(CONFIG_VHOST_VSOCK) += vhost-vsock.o
obj-y += virtio-crypto.o
obj-$(CONFIG_VIRTIO_PCI) += virtio-crypto-pci.o
