QEMU_PROG_FUZZ=qemu-fuzz-$(TARGET_NAME)$(EXESUF)
fuzz-obj-y = $(libqos-obj-y)
fuzz-obj-y += tests/libqtest.o
fuzz-obj-y += tests/fuzz/fuzz.o
fuzz-obj-y += tests/fuzz/fork_fuzz.o
fuzz-obj-y += tests/fuzz/qos_fuzz.o

fuzz-obj-y += tests/fuzz/i440fx_fuzz.o
fuzz-obj-y += tests/fuzz/virtio_net_fuzz.o

FUZZ_LDFLAGS += -Xlinker -T$(SRC_PATH)/tests/fuzz/fork_fuzz.ld
