HOST_CC = gcc

TESTS_PATH = $(SRC_PATH)/tests/tcg/tricore

LDFLAGS = -T$(TESTS_PATH)/link.ld
ASFLAGS =

QEMU_OPTS += -M tricore_testboard -nographic -kernel

TESTS += test_abs.tst
TESTS += test_bmerge.tst
TESTS += test_clz.tst
TESTS += test_dvstep.tst
TESTS += test_fadd.tst
TESTS += test_fmul.tst
TESTS += test_ftoi.tst
TESTS += test_madd.tst
TESTS += test_msub.tst

%.pS: $(TESTS_PATH)/%.S
	$(HOST_CC) -E -o $@ $<

%.o: %.pS
	$(AS) $(ASFLAGS) -o $@ $<

%.tst: %.o
	$(LD) $(LDFLAGS) $< -o $@
