CROSS_CC ?= aarch64-linux-gnu-gcc
LDFLAGS := -nostdlib -shared -Wl,-T,vdso.ld \
	   -Wl,-h,linux-vdso.so.1 -Wl,--hash-style=sysv -Wl,--build-id=sha1

all: vdso-le.so vdso-be.so

vdso-le.so: vdso.S vdso.ld Makefile.vdso
	$(CROSS_CC)  $(LDFLAGS) -mlittle-endian vdso.S -o $@

vdso-be.so: vdso.S vdso.ld Makefile.vdso
	$(CROSS_CC)  $(LDFLAGS) -mbig-endian vdso.S -o $@
