[package]
name = "trace"
version = "0.1.0"
authors = ["Tanish Desai <tanishdesai37@gmail.com>"]
description = "QEMU tracing infrastructure support"
resolver = "2"
publish = false

edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
libc = { workspace = true }

[lints]
workspace = true
