# -*- Mode: makefile -*-
#
# m68k specific tweaks - specifically masking out broken tests
#

VPATH += $(SRC_PATH)/tests/tcg/m68k
TESTS += trap denormal packeddecimal-1 packeddecimal-2

run-packeddecimal-%: QEMU_OPTS += -cpu m68020
