# -*- Mode: makefile -*-
# RISC-V specific tweaks

config-cc.mak: Makefile
	$(quiet-@)( \
	    $(call cc-option,-mrv64g_zk, CROSS_CC_HAS_ZK) \
	) 3> config-cc.mak

-include config-cc.mak

VPATH += $(SRC_PATH)/tests/tcg/riscv64
TESTS += test-div
TESTS += noexec

# Disable compressed instructions for test-noc
TESTS += test-noc
test-noc: LDFLAGS = -nostdlib -static
run-test-noc: QEMU_OPTS += -cpu rv64,c=false

ifneq ($(CROSS_CC_HAS_ZK),)
TESTS += test-aes
test-aes: CFLAGS += -O -march=rv64gzk
run-test-aes: QEMU_OPTS += -cpu rv64,zk=on
endif
