#
# RISC-V system tests
#

TEST_SRC = $(SRC_PATH)/tests/tcg/riscv64
VPATH += $(TEST_SRC)

LINK_SCRIPT = $(TEST_SRC)/semihost.ld
LDFLAGS = -T $(LINK_SCRIPT)
CFLAGS += -march=rv64gcv -mabi=lp64d -g -Og

%.o: %.S
	$(CC) $(CFLAGS) $< -Wa,--noexecstack -c -o $@
%: %.o $(LINK_SCRIPT)
	$(LD) $(LDFLAGS) $< -o $@

QEMU_OPTS += -M virt -cpu rv64,v=true -display none -semihosting -device loader,file=

EXTRA_RUNS += run-issue1060
run-issue1060: issue1060
	$(call run-test, $<, $(QEMU) $(QEMU_OPTS)$<)

EXTRA_RUNS += run-test-mepc-masking
run-test-mepc-masking: test-mepc-masking
	$(call run-test, $<, $(QEMU) $(QEMU_OPTS)$<)

EXTRA_RUNS += run-vlsseg8e32
run-vlsseg8e32: test-vlsseg8e32
	$(call run-test, $<, $(QEMU) $(QEMU_OPTS)$<)

# We don't currently support the multiarch system tests
undefine MULTIARCH_TESTS
