# -*- Mode: makefile -*-
# RISC-V specific tweaks

VPATH += $(SRC_PATH)/tests/tcg/riscv64
TESTS += test-div
TESTS += noexec

# Disable compressed instructions for test-noc
TESTS += test-noc
test-noc: LDFLAGS = -nostdlib -static
run-test-noc: QEMU_OPTS += -cpu rv64,c=false

TESTS += test-aes
run-test-aes: QEMU_OPTS += -cpu rv64,zk=on

# Vector load test
TESTS += test-rvv-ldst test-rvv-ldst-intrinsics
test-rvv-ldst-intrinsics test-rvv-ldst: CFLAGS += -march=rv64gcv
test-rvv-ldst: LDFLAGS = -nostdlib -static
test-rvv-ldst-intrinsics: LDFLAGS = -static
run-test-rvv-ldst-intrinsics run-test-rvv-ldst: QEMU_OPTS += -cpu max

# Re-run the vector tests at each supported VLEN
TEST_RVV_VLENS = 128 256 512 1024
EXTRA_RUNS += $(patsubst %,run-test-rvv-ldst-vlen%,$(TEST_RVV_VLENS))
run-test-rvv-ldst-vlen%: test-rvv-ldst
	$(call run-test, $@, env QEMU=$(QEMU) $(QEMU) $(QEMU_OPTS) -cpu max$(COMMA)vlen=$* $<, \
		test-rvv-ldst with vlen=$*)

EXTRA_RUNS += $(patsubst %,run-test-rvv-ldst-intrinsics-vlen%,$(TEST_RVV_VLENS))
run-test-rvv-ldst-intrinsics-vlen%: test-rvv-ldst-intrinsics
	$(call run-test, $@, env QEMU=$(QEMU) $(QEMU) $(QEMU_OPTS) -cpu max$(COMMA)vlen=$* $<, \
		test-rvv-ldst-intrinsics with vlen=$*)

# Test for fcvtmod
TESTS += test-fcvtmod
test-fcvtmod: CFLAGS += -march=rv64imafdc
test-fcvtmod: LDFLAGS += -static
run-test-fcvtmod: QEMU_OPTS += -cpu rv64,d=true,zfa=true
