# -*- Mode: makefile -*-
# RISC-V specific tweaks

# Not all environments have compilers with vector intrinsics yet.
HAVE_RISCV_VECTOR_INTRINSICS := $(shell echo '#ifndef __riscv_v_intrinsic\n#error\n#endif' |  \
                                  $(CC) -march=rv64gcv -E -x c - >/dev/null 2>&1 && echo y)

VPATH += $(SRC_PATH)/tests/tcg/riscv64
TESTS += test-div
TESTS += noexec

# Disable compressed instructions for test-noc
TESTS += test-noc
test-noc: LDFLAGS = -nostdlib -static
run-test-noc: QEMU_OPTS += -cpu rv64,c=false

TESTS += test-aes
run-test-aes: QEMU_OPTS += -cpu rv64,zk=on

# Test for fcvtmod
TESTS += test-fcvtmod
test-fcvtmod: CFLAGS += -march=rv64imafdc
test-fcvtmod: LDFLAGS += -static
run-test-fcvtmod: QEMU_OPTS += -cpu rv64,d=true,zfa=true

# Test for vstart >= vl
TESTS += test-vstart-overflow
test-vstart-overflow: CFLAGS += -march=rv64gcv
run-test-vstart-overflow: QEMU_OPTS += -cpu rv64,v=on

ifeq ($(HAVE_RISCV_VECTOR_INTRINSICS),y)
# Test for interrupted vector instructions
TESTS += test-interrupted-v
test-interrupted-v: CFLAGS += -march=rv64gcv
run-test-interrupted-v: QEMU_OPTS += -cpu rv64,v=on
endif
