# -*- Mode: makefile -*-
#
# SuperH specific tweaks
#

VPATH += $(SRC_PATH)/tests/tcg/sh4

test-macl: CFLAGS += -O -g
TESTS += test-macl

test-macw: CFLAGS += -O -g
TESTS += test-macw

test-addv: CFLAGS += -O -g
TESTS += test-addv

test-subv: CFLAGS += -O -g
TESTS += test-subv

test-fpu-fipr: CFLAGS += -O -g
TESTS += test-fpu-fipr

test-fpu-ftrv: CFLAGS += -O -g
TESTS += test-fpu-ftrv

