# All jobs should run successfully in an environment setup by the
# scripts/ci/setup/build-environment.yml task:
# "Install basic packages to build QEMU on Ubuntu/Debian"

.debian_ppc64le_template:
  extends: .custom_runner_template
  needs: []
  stage: build
  tags:
    - debian_13
    - ppc64le
  rules:
    - if: '$CI_PROJECT_NAMESPACE == "qemu-project" && $CI_COMMIT_BRANCH =~ /^staging/'
    - if: "$PPC64LE_RUNNER_AVAILABLE"
  before_script:
    - source scripts/ci/gitlab-ci-section
    - section_start setup "Pre-script setup"
    - JOBS=$(expr $(nproc) - 2)
    - section_end setup
  script:
    - mkdir build
    - cd build
    - section_start configure "Running configure"
    - ../configure $CONFIGURE_ARGS ||
          { cat config.log meson-logs/meson-log.txt && exit 1; }
    - section_end configure
    - section_start build "Building QEMU"
    - make --output-sync -j"$JOBS"
    - section_end build
    - section_start test "Running tests"
    - if test -n "$MAKE_CHECK_ARGS";
      then
        make -j"$JOBS" $MAKE_CHECK_ARGS ;
      fi
    - section_end test

debian-13-ppc64le-default:
  extends: .debian_ppc64le_template
  variables:
    MAKE_CHECK_ARGS: check
