# All ubuntu-24.04 jobs should run successfully in an environment
# setup by the scripts/ci/setup/ubuntu/build-environment.yml task
# "Install basic packages to build QEMU on Ubuntu 24.04"

ubuntu-24.04-aarch32-all:
 extends: .custom_runner_template
 needs: []
 stage: build
 tags:
 - ubuntu_24.04
 - aarch32
 rules:
 - if: '$CI_PROJECT_NAMESPACE == "qemu-project" && $CI_COMMIT_BRANCH =~ /^staging/'
   when: manual
   allow_failure: true
 - if: "$AARCH32_RUNNER_AVAILABLE"
   when: manual
   allow_failure: true
 before_script:
   - source scripts/ci/gitlab-ci-section
   - section_start setup "Pre-script setup"
   - JOBS=$(expr $(nproc) - 4)
   - section_end setup
 script:
 - mkdir build
 - cd build
 - section_start configure "Running configure"
 - ../configure --cross-prefix=arm-linux-gnueabihf-
   || { cat config.log meson-logs/meson-log.txt; exit 1; }
 - section_end configure
 - section_start build "Building QEMU"
 - make --output-sync -j"$JOBS"
 - section_end build
 - section_start test "Running tests"
 - make --output-sync -j"$JOBS" check
 - section_end test
