qom-obj-y = object.o container.o qom-qobject.o
qom-obj-y += object_interfaces.o

common-obj-$(CONFIG_SOFTMMU) += qom-hmp-cmds.o qom-qmp-cmds.o

remote-pci-obj-$(CONFIG_MPQEMU) += object.o qom-qobject.o container.o
remote-pci-obj-$(CONFIG_MPQEMU) += object_interfaces.o
