.PHONY: build-native
build-native: $(NATIVE_TARGETS:%=build-native-library-%)
$(NATIVE_TARGETS:%=build-native-library-%): build-native-library-%:
	$(call quiet-command, \
	    $(MAKE) -C common-user/native/$* $(SUBDIR_MAKEFLAGS), \
	"BUILD","$* native library")
# endif

all: build-native
