# -*- Mode: makefile -*-
#
# MIPS64 - included from tests/tcg/Makefile.target
#

MIPS64_SRC=$(SRC_PATH)/tests/tcg/mips64

# Set search path for all sources
VPATH += $(MIPS64_SRC)

ifeq ($(CONFIG_PLUGIN),y)
# Require no ABI calls to avoid $t9-relative .got address calculation on MIPS64
test-plugin-skip-syscalls: CFLAGS+=-mno-abicalls -fno-pie
test-plugin-skip-syscalls: LDFLAGS+=-no-pie
endif
