/* List of comma-separated changed AML files to ignore */
"tests/data/acpi/aarch64/virt/HEST",
"tests/data/acpi/aarch64/virt/DSDT",
"tests/data/acpi/aarch64/virt/DSDT.acpihmatvirt",
"tests/data/acpi/aarch64/virt/DSDT.acpipcihp",
"tests/data/acpi/aarch64/virt/DSDT.hpoffacpiindex",
"tests/data/acpi/aarch64/virt/DSDT.memhp",
"tests/data/acpi/aarch64/virt/DSDT.pxb",
"tests/data/acpi/aarch64/virt/DSDT.topology",
"tests/data/acpi/aarch64/virt/DSDT.viot",
