#ifndef BLOCK_GENERATED_CO_WRAPPER_H
#define BLOCK_GENERATED_CO_WRAPPER_H

/*
 * generated_co_wrapper
 * Function specifier, which does nothing but marking functions to be
 * generated by scripts/coroutine-wrapper.py
 */
#define generated_co_wrapper

#endif /* BLOCK_GENERATED_CO_WRAPPER_H */
