ifeq ($(CONFIG_RDMA),y)
obj-$(CONFIG_PVRDMA) += rdma_utils.o rdma_backend.o rdma_rm.o
obj-$(CONFIG_PVRDMA) += vmw/pvrdma_dev_ring.o vmw/pvrdma_cmd.o \
                        vmw/pvrdma_qp_ops.o vmw/pvrdma_main.o
endif

