#!/bin/sh
# Copyright (c) 2016 Red Hat, Inc. and/or its affiliates
# This work is licensed under the terms of the GNU GPL, version 2 or later.
# See the COPYING file in the top-level directory.
#
# Author: dgilbert@redhat.com

ASMFILE=tests/migration/x86-a-b-bootblock.s
HEADER=tests/migration/x86-a-b-bootblock.h

if [ ! -e "$ASMFILE" ]
then
  echo "Couldn't find $ASMFILE" >&2
  exit 1
fi

ASM_WORK_DIR=/tmp/X86BB$$
mkdir $ASM_WORK_DIR &&
as --32 -march=i486 "$ASMFILE" -o $ASM_WORK_DIR/bb.o &&
objcopy -O binary $ASM_WORK_DIR/bb.o $ASM_WORK_DIR/bb.boot &&
dd if=$ASM_WORK_DIR/bb.boot of=$ASM_WORK_DIR/bb.bootsect \
  bs=256 count=2 skip=124 &&
xxd -i $ASM_WORK_DIR/bb.bootsect |
sed -e 's/_tmp.*_bootsect/x86_bootsect/' -e 's/.*int.*//' > \
  $ASM_WORK_DIR/bb.hex &&
cat - $ASM_WORK_DIR/bb.hex <<HERE > "$HEADER"
/* This file is automatically generated from
 * tests/migration/x86-a-b-bootblock.s, edit that and then run
 * tests/migration/rebuild-x86-bootblock.sh to update,
 * and then remember to send both in your patch submission.
 */
HERE

rm $ASM_WORK_DIR/bb.hex $ASM_WORK_DIR/bb.bootsect $ASM_WORK_DIR/bb.boot
rm $ASM_WORK_DIR/bb.o
rmdir $ASM_WORK_DIR

