#!/bin/sh
# Copyright (c) 2018 Red Hat, Inc. and/or its affiliates
# This work is licensed under the terms of the GNU GPL, version 2 or later.
# See the COPYING file in the top-level directory.

srcdir=$(dirname $0)
fwdir="$srcdir"/../../pc-bios/s390-ccw
SRCFILE=$srcdir/s390x-a-b.c
HEADER=$srcdir/s390x-a-b.h

if [ ! -e "$SRCFILE" ]; then
    echo "Couldn't find $SRCFILE" >&2
    exit 1
fi

if [ $(uname -m) = "s390x" ]; then
    cc=gcc
    strip=strip
else
    cc=s390x-linux-gnu-gcc
    strip=s390x-linux-gnu-strip
fi

tmpdir=$(mktemp -d --tmpdir X86BB.XXXXXX)
$cc -ffreestanding -fno-delete-null-pointer-checks -fPIE -Os \
    -msoft-float -march=z900 -fno-asynchronous-unwind-tables -Wl,-pie \
    -Wl,--build-id=none -nostdlib -I"$fwdir" "$fwdir"/start.S \
    "$fwdir"/sclp.c "$srcdir"/s390x-a-b.c -o "$tmpdir"/s390x-a-b.elf &&
$strip --strip-unneeded "$tmpdir"/s390x-a-b.elf &&
cd "$tmpdir" &&
xxd -i s390x-a-b.elf | sed -e 's/.*int.*//' > "$tmpdir"/s390x-a-b.hex &&
cd "$OLDPWD" &&
cat - "$tmpdir"/s390x-a-b.hex <<HERE > "$HEADER"
/*
 * This file is automatically generated from tests/migration/s390x-a-b.c, edit
 * that and then run tests/migration/s390x-a-b-rebuild.sh to update, and then
 * remember to send both in your patch submission.
 */
HERE

rm "$tmpdir"/s390x-a-b.hex "$tmpdir"/s390x-a-b.elf
cd .. && rmdir "$tmpdir"
