  ETHTOOL(ETHTOOL_GSET, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_cmd)))
  ETHTOOL(ETHTOOL_SSET, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_cmd)))
  ETHTOOL(ETHTOOL_GDRVINFO, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_drvinfo)))
  ETHTOOL(ETHTOOL_GREGS, ETHT_RW, MK_PTR(MK_STRUCT(STRUCT_ethtool_regs)))
  ETHTOOL(ETHTOOL_GWOL, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_wolinfo)))
  ETHTOOL(ETHTOOL_SWOL, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_wolinfo)))
  ETHTOOL(ETHTOOL_GMSGLVL, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_SMSGLVL, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_GEEE, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_eee)))
  ETHTOOL(ETHTOOL_SEEE, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_eee)))
  ETHTOOL(ETHTOOL_NWAY_RST, 0, TYPE_NULL)
  ETHTOOL(ETHTOOL_GLINK, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_GEEPROM, ETHT_RW, MK_PTR(MK_STRUCT(STRUCT_ethtool_eeprom)))
  ETHTOOL(ETHTOOL_SEEPROM, ETHT_RW, MK_PTR(MK_STRUCT(STRUCT_ethtool_eeprom)))
  ETHTOOL(ETHTOOL_GCOALESCE, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_coalesce)))
  ETHTOOL(ETHTOOL_SCOALESCE, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_coalesce)))
  ETHTOOL(ETHTOOL_GRINGPARAM, ETHT_R,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_ringparam)))
  ETHTOOL(ETHTOOL_SRINGPARAM, ETHT_W,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_ringparam)))
  ETHTOOL(ETHTOOL_GPAUSEPARAM, ETHT_R,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_pauseparam)))
  ETHTOOL(ETHTOOL_SPAUSEPARAM, ETHT_W,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_pauseparam)))
  ETHTOOL(ETHTOOL_TEST, ETHT_RW, MK_PTR(MK_STRUCT(STRUCT_ethtool_test)))
  ETHTOOL(ETHTOOL_GSTRINGS, ETHT_RW, MK_PTR(MK_STRUCT(STRUCT_ethtool_gstrings)))
  ETHTOOL(ETHTOOL_PHYS_ID, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_GSTATS, ETHT_RW, MK_PTR(MK_STRUCT(STRUCT_ethtool_stats)))
  ETHTOOL(ETHTOOL_GPERMADDR, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_perm_addr)))
  ETHTOOL(ETHTOOL_GFLAGS, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_SFLAGS, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_GPFLAGS, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_SPFLAGS, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_GRXFH, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_rxnfc_get_set_rxfh)))
  ETHTOOL(ETHTOOL_GRXRINGS, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_rxnfc_rss_context)))
  ETHTOOL(ETHTOOL_GRXCLSRLCNT, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_rxnfc_rule_cnt)))
  ETHTOOL(ETHTOOL_GRXCLSRULE, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_rxnfc_rss_context)))
  ETHTOOL(ETHTOOL_GRXCLSRLALL, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_rxnfc_rule_locs)))
  ETHTOOL(ETHTOOL_SRXFH, ETHT_W,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_rxnfc_get_set_rxfh)))
  ETHTOOL(ETHTOOL_SRXCLSRLDEL, ETHT_W,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_rxnfc_rss_context)))
  ETHTOOL(ETHTOOL_SRXCLSRLINS, ETHT_W,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_rxnfc_rss_context)))
  ETHTOOL(ETHTOOL_FLASHDEV, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_flash)))
  ETHTOOL(ETHTOOL_RESET, ETHT_RW, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_GSSET_INFO, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_sset_info)))
  ETHTOOL(ETHTOOL_GRXFHINDIR, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_rxfh_indir)))
  ETHTOOL(ETHTOOL_SRXFHINDIR, ETHT_W,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_rxfh_indir)))
  ETHTOOL_SPECIAL(ETHTOOL_GRSSH, ETHT_RW, do_ethtool_get_rxfh,
                  MK_PTR(MK_STRUCT(STRUCT_ethtool_rxfh)))
  ETHTOOL(ETHTOOL_SRSSH, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_rxfh)))
  ETHTOOL(ETHTOOL_GFEATURES, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_gfeatures)))
  ETHTOOL(ETHTOOL_SFEATURES, ETHT_W,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_sfeatures)))
  ETHTOOL(ETHTOOL_GTXCSUM, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_GRXCSUM, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_GSG, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_GTSO, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_GGSO, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_GGRO, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_STXCSUM, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_SRXCSUM, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_SSG, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_STSO, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_SGSO, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_SGRO, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_value)))
  ETHTOOL(ETHTOOL_GCHANNELS, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_channels)))
  ETHTOOL(ETHTOOL_SCHANNELS, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_channels)))
  ETHTOOL(ETHTOOL_SET_DUMP, ETHT_W,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_dump_no_data)))
  ETHTOOL(ETHTOOL_GET_DUMP_FLAG, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_dump_no_data)))
  ETHTOOL(ETHTOOL_GET_DUMP_DATA, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_dump)))
  ETHTOOL(ETHTOOL_GET_TS_INFO, ETHT_R,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_ts_info)))
  ETHTOOL(ETHTOOL_GMODULEINFO, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_modinfo)))
  ETHTOOL(ETHTOOL_GMODULEEEPROM, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_eeprom)))
  ETHTOOL(ETHTOOL_GTUNABLE, ETHT_RW, MK_PTR(MK_STRUCT(STRUCT_ethtool_tunable)))
  ETHTOOL(ETHTOOL_STUNABLE, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_tunable)))
  ETHTOOL(ETHTOOL_GPHYSTATS, ETHT_RW, MK_PTR(MK_STRUCT(STRUCT_ethtool_stats)))
  ETHTOOL(ETHTOOL_PERQUEUE, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_per_queue_op)))
  ETHTOOL(ETHTOOL_GLINKSETTINGS, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_link_settings)))
  ETHTOOL(ETHTOOL_SLINKSETTINGS, ETHT_W,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_link_settings)))
  ETHTOOL(ETHTOOL_PHY_GTUNABLE, ETHT_RW,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_tunable)))
  ETHTOOL(ETHTOOL_PHY_STUNABLE, ETHT_W,
          MK_PTR(MK_STRUCT(STRUCT_ethtool_tunable)))
  ETHTOOL(ETHTOOL_GFECPARAM, ETHT_R, MK_PTR(MK_STRUCT(STRUCT_ethtool_fecparam)))
  ETHTOOL(ETHTOOL_GFECPARAM, ETHT_W, MK_PTR(MK_STRUCT(STRUCT_ethtool_fecparam)))
