#
# ARC softmmu tests
#

ARC_SRC = $(SRC_PATH)/tests/tcg/arc
ARC_ALL = $(filter-out $(ARC_SRC)/ivt.S,$(wildcard $(ARC_SRC)/*.S))
ARC_TESTS = $(patsubst $(ARC_SRC)/%.S, %, $(ARC_ALL))

# Filter out common blobs and broken tests
ARC_BROKEN_TESTS = check_carry check_excp_jumpdl_mmu
ARC_USABLE_TESTS = $(filter-out $(ARC_BROKEN_TESTS), $(ARC_TESTS))

# add to the list of tests
TESTS += $(ARC_USABLE_TESTS)
VPATH += $(ARC_SRC)

QEMU_OPTS+=-M arc-sim -m 3G -nographic -no-reboot -serial stdio -global cpu.mpu-numreg=8 -kernel

CROSS = arc-elf32-

ASFLAGS = -mcpu=archs
LDFLAGS = --specs=qemu.specs -T $(ARC_SRC)/tarc.ld -nostartfiles -nostdlib
MMU_LDFLAGS = --specs=qemu.specs -T $(ARC_SRC)/tarc_mmu.ld -nostartfiles -nostdlib
CRT = ivt.o

SIM = ../../../qemu-system-arc
SIM_FLAGS = -M arc-sim -m 3G -nographic -no-reboot -monitor none \
	            -serial stdio -global cpu.mpu-numreg=8 -kernel

$(ARC_USABLE_TESTS): $(CRT) Makefile.softmmu-target

# special rule for common blobs
%.o: %.S
	cd ${BUILD_DIR} && \
	$(CC) -I$(ARC_SRC) $($*ASFLAGS) $(ASFLAGS) $(EXTRACFLAGS) -c $< -o ./$@

%_mmu: %_mmu.o
	cd ${BUILD_DIR} && \
	$(CC) -I$(ARC_SRC) $(ASFLAGS) $(EXTRA_CFLAGS) $< -o $@ $(MMU_LDFLAGS) $(NOSTDFLAGS) $(CRT)

%: %.o
	cd ${BUILD_DIR} && \
	$(CC) -I$(ARC_SRC) $(ASFLAGS) $(EXTRA_CFLAGS) $< -o $@ $(LDFLAGS) $(NOSTDFLAGS) $(CRT)
