#
# ARC softmmu tests
#

ARC_SRC = $(SRC_PATH)/tests/tcg/arc
ARC_ALL = $(filter-out $(ARC_SRC)/ivt.S,$(wildcard $(ARC_SRC)/*.S))
ARC_TESTS = $(patsubst $(ARC_SRC)/%.S, %, $(ARC_ALL))
# Filter out common blobs and broken tests
ARC_BROKEN_TESTS = ivt
ARC_USABLE_TESTS = $(filter-out $(ARC_BROKEN_TESTS), $(ARC_TESTS))

# add to the list of tests
TESTS += $(ARC_USABLE_TESTS)
VPATH += $(ARC_SRC)

QEMU_OPTS+=-M arc-sim -m 3G -nographic -no-reboot -serial stdio -global cpu.mpu-numreg=8 -kernel

#CROSS = arc-elf32-
#
#CC = $(CROSS)gcc
#LD = $(CROSS)ld
#AS = $(CROSS)as

ASFLAGS = -mcpu=archs
LDFLAGS = --specs=qemu.specs -T $(ARC_SRC)/tarc.ld -nostartfiles -nostdlib

CRT = ivt.o

$(ARC_USABLE_TESTS): $(CRT) Makefile.softmmu-target

# special rule for common blobs
%.o: %.S
$(CC) -I$(ARC_SRC) $($*ASFLAGS) $(ASFLAGS) $(EXTRACFLAGS) -c $< -o $@

%: %.S
$(CC) -I$(ARC_SRC) $(ASFLAGS) $(EXTRA_CFLAGS) $< -o $@ $(LDFLAGS) $(NOSTDFLAGS) $(CRT)
