# -*- Mode: makefile -*-
#
# ARM - included from tests/tcg/Makefile.target
#

ARM_SRC=$(SRC_PATH)/tests/tcg/arm

# Set search path for all sources
VPATH 		+= $(ARM_SRC)

TESTS += hello-arm test-arm-iwmmxt

hello-arm: CFLAGS+=-marm -ffreestanding
hello-arm: LDFLAGS+=-nostdlib

test-arm-iwmmxt: CFLAGS+=-marm -march=iwmmxt -mabi=aapcs
test-arm-iwmmxt: test-arm-iwmmxt.S
	$(CC) $(CFLAGS) $< -o $@ $(LDFLAGS)
