# -*- Mode: makefile -*-
#
# HPPA specific tweaks - specifically masking out broken tests

run-linux-test: linux-test
	$(call quiet-command, /bin/true, "BROKEN TEST", "$< SKIPPED on $(TARGET_NAME)")

# Currently broken for -p
run-test-mmap: test-mmap
	$(call quiet-command, $(QEMU) $< > test-mmap.out, "TEST", "$< (default) on $(TARGET_NAME)")
