obj-y += misc.o
common-obj-y += monitor.o qmp.o hmp.o
common-obj-y += qmp-cmds.o qmp-cmds-control.o
common-obj-y += hmp-cmds.o
qmp-cmds.o-cflags += $(SPICE_CFLAGS)
hmp-cmds.o-cflags += $(SPICE_CFLAGS)
misc.o-cflags += $(SPICE_CFLAGS)

storage-daemon-obj-y += monitor.o qmp.o qmp-cmds-control.o
