# SPDX-License-Identifier: GPL-2.0-or-later
#
# RISC-V 32-bit system tests
#

TEST_SRC = $(SRC_PATH)/tests/tcg/riscv32
VPATH += $(TEST_SRC)

LINK_SCRIPT = $(SRC_PATH)/tests/tcg/riscv64/semihost.ld
LDFLAGS = -m elf32lriscv -T $(LINK_SCRIPT)
CFLAGS += -g -Og $(EXTRA_CFLAGS) -march=rv32im_zicsr -mabi=ilp32

%.o: %.S
	$(CC) $(CFLAGS) $< -Wa,--noexecstack -c -o $@
%: %.o $(LINK_SCRIPT)
	$(LD) $(LDFLAGS) $< -o $@

QEMU_OPTS += -M virt -display none -semihosting -device loader,file=

TESTS += pmu-fixed-rv32
run-pmu-fixed-rv32: pmu-fixed-rv32
	$(call run-test, $<, $(QEMU) -cpu max -icount shift=0 $(QEMU_OPTS)$<)

TESTS += smcdeleg-minh-rv32
run-smcdeleg-minh-rv32: smcdeleg-minh-rv32
	$(call run-test, $<, $(QEMU) -cpu max $(QEMU_OPTS)$<)

TESTS += pmu-minstretcfg-rv32
run-pmu-minstretcfg-rv32: pmu-minstretcfg-rv32
	$(call run-test, $<, $(QEMU) -cpu max $(QEMU_OPTS)$<)

TESTS += smcdeleg-event-rv32
run-smcdeleg-event-rv32: smcdeleg-event-rv32
	$(call run-test, $<, $(QEMU) -cpu max $(QEMU_OPTS)$<)

TESTS += smcdeleg-counter-rv32
run-smcdeleg-counter-rv32: smcdeleg-counter-rv32
	$(call run-test, $<, $(QEMU) -cpu max $(QEMU_OPTS)$<)

TESTS += sscofpmf-event-rv32
run-sscofpmf-event-rv32: sscofpmf-event-rv32
	$(call run-test, $<, $(QEMU) -cpu max -icount shift=0 $(QEMU_OPTS)$<)
