#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later

missing=0
present=0

grep -E '^(R|M):' MAINTAINERS | \
sed -E -e 's/^(M|R): //' -e 's/ <.*//' | \
sort | uniq > names.txt
while IFS= read -r NAME
do
  grep "$NAME" .gitlab-map-{auto,manual} > /dev/null
  if test $? != 0
  then
    echo "Missing GitLab handle: $NAME"
    missing=$(($missing + 1))
  else
    present=$(($present + 1))
  fi
done < names.txt
rm -f names.txt

echo "GitLab handles missing: $missing / present: $present"
