#!/bin/sh

printifnotrst()
{
    test $outsiderst -eq 1 && printf "%s\n" "$str"
}
hxtoh()
{
    outsiderst=1
    # .name for HMP
    seenname=0
    while read -r str; do
        case $str in
            HXCOMM*)
            ;;
            SRST*)
              if [ $outsiderst -eq 0 ]
              then
                echo "Error: SRST inside another RST" >&2
                exit 1
              fi
              # consume the name
              seenname=0
              outsiderst=0
            ;;
            ERST*)
              if [ $outsiderst -eq 1 ]
              then
                echo "Error: ERST already outside RST" >&2
                exit 1
              fi
              outsiderst=1
            ;;
            # Note the space at the start - we need to exclude something.name
             .name*)
              if [ $seenname -eq 1 ]
              then
                echo "Error: Seen another .name, maybe missing docs?" >&2
                exit 1
              fi
              seenname=1
              printifnotrst
            ;;
            *)
            printifnotrst
            ;;
        esac
    done
}

case "$1" in
"-h") hxtoh ;;
*) exit 1 ;;
esac < "$2"

exit 0
