#!/bin/sh

hxtoh()
{
    outsiderst=1
    while read -r str; do
        case $str in
            HXCOMM*)
            ;;
            SRST*)
              if [ $outsiderst -eq 0 ]
              then
                echo "Error: SRST inside another RST" >&2
                exit 1
              fi
              outsiderst=0
            ;;
            ERST*)
              if [ $outsiderst -eq 1 ]
              then
                echo "Error: ERST already outside RST" >&2
                exit 1
              fi
              outsiderst=1
            ;;
            *)
            test $outsiderst -eq 1 && printf "%s\n" "$str"
            ;;
        esac
    done
}

case "$1" in
"-h") hxtoh ;;
*) exit 1 ;;
esac < "$2"

exit 0
