#!/bin/bash -e
#
# QEMU Release Script
#
# Copyright IBM, Corp. 2012
#
# Authors:
#  Anthony Liguori <aliguori@us.ibm.com>
#
# This work is licensed under the terms of the GNU GPLv2 or later.
# See the COPYING file in the top-level directory.

src="$1"
version="$2"
destination=qemu-${version}

git clone "${src}" ${destination}
pushd ${destination}
git checkout "v${version}"
git submodule update --init
(cd roms/seabios && git describe --tags --long --dirty > .version)
(cd roms/skiboot && ./make_version.sh > .version)

# Fetch edk2 submodule's submodules to get their license information.
# Edk2 is distributed under permissive licenses, so we don't have to
# include the full source tree here (which is bigger than QEMU's sources)
# as long as we provide the license information in the tarball.
#
# A more uniform way to handle this sort of situation would be nice, but we
# don't necessarily have much control over how a submodule handles its
# submodule dependencies, so we continue to handle these on a case-by-case
# basis for now.
cd roms/edk2
git submodule update --init --depth 1 -- \
        ArmPkg/Library/ArmSoftFloatLib/berkeley-softfloat-3 \
        BaseTools/Source/C/BrotliCompress/brotli \
        CryptoPkg/Library/OpensslLib/openssl
mv ArmPkg/Library/ArmSoftFloatLib/berkeley-softfloat-3/COPYING.txt \
   License-softfloat.txt
mv BaseTools/Source/C/BrotliCompress/brotli/LICENSE License-brotli.txt
mv CryptoPkg/Library/OpensslLib/openssl/LICENSE License-openssl.txt
edk2rev=$(git rev-parse --short=12 HEAD)
rm -r $(ls | grep -v License) .[a-z]*
cat > sources.txt <<EOF
The edk2 sources can be downloaded from:

https://github.com/tianocore/edk2/archive/${edk2rev}.tar.gz
EOF
cd ../..

popd
tar --exclude=.git -cjf ${destination}.tar.bz2 ${destination}
rm -rf ${destination}
