#!/usr/bin/env python3

# This script takes as input the Registers.json file delivered in
# the AARCHMRS Features Model downloadable from the Arm Developer
# A-Profile Architecture Exploration Tools page:
# https://developer.arm.com/Architectures/A-Profile%20Architecture#Downloads
# and outputs the list of ID regs in target/arm/cpu-sysregs.h.inc
# under the form of DEF(<name>, <op0>, <op1>, <crn>, <crm>, <op2>)
#
# Copyright (C) 2026 Red Hat, Inc.
#
# Authors: Eric Auger <eric.auger@redhat.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later


import json
import os
import sys
from aarch64_sysreg_helpers import extract_idregs_from_registers_json

if __name__ == "__main__":
    # Single arg expected: the path to the Registers.json file
    if len(sys.argv) < 2:
        print("Usage: python scripts/update-aarch64-cpu-sysregs-header.py "
              "<path_to_registers_json>")
        sys.exit(1)
    else:
        json_file_path = sys.argv[1]

    extracted_registers = extract_idregs_from_registers_json(json_file_path)

    if extracted_registers:
        output_list = extracted_registers.items()

        # Sort by register name
        sorted_output = sorted(output_list, key=lambda item: item[0])

        # format lines as DEF(<name>, <op0>, <op1>, <crn>, <crm>, <op2>)
        final_output = ""
        for reg_name, encoding in sorted_output:
            reformatted_encoding = encoding.replace(" ", ", ")
            final_output += f"DEF({reg_name}, {reformatted_encoding})\n"

        with open("target/arm/cpu-sysregs.h.inc", 'w') as f:
            f.write("/* SPDX-License-Identifier: GPL-2.0-or-later */\n\n")
            f.write("/* This file is autogenerated by ")
            f.write("scripts/update-aarch64-cpu-sysregs-header.py */\n")
            f.write("/* DEF(<name>, <op0>, <op1>, <crn>, <crm>, <op2>) */\n\n")
            f.write(final_output)
        print("updated target/arm/cpu-sysregs.h.inc")
