#include "qemu/osdep.h"
#include <windows.h>
#include <io.h>
#include "qapi/error.h"
#include "qemu/sockets.h"
#include "guest-agent-core.h"
#include "channel-common.h"

typedef struct GAChannelReadState {
    guint thread_id;
    uint8_t *buf;
    size_t buf_size;
    size_t cur; /* current buffer start */
    size_t pending; /* pending buffered bytes to read */
    OVERLAPPED ov;
    bool ov_pending; /* whether on async read is outstanding */
} GAChannelReadState;

struct GAChannel {
    GAChannelCommon common;

    int listen_fd;
    int client_fd;

    HANDLE handle;
    GAChannelReadState rstate;
    GIOCondition pending_events; /* TODO: use GAWatch.pollfd.revents */
    GSource *source;
};

typedef struct GAWatch {
    GSource source;
    GPollFD pollfd;
    GAChannel *channel;
    GIOCondition events_mask;
} GAWatch;

/*
 * Called by glib prior to polling to set up poll events if polling is needed.
 *
 */
static gboolean ga_channel_prepare(GSource *source, gint *timeout_ms)
{
    GAWatch *watch = (GAWatch *)source;
    GAChannel *c = (GAChannel *)watch->channel;
    GAChannelReadState *rs = &c->rstate;
    DWORD count_read, count_to_read = 0;
    bool success;
    GIOCondition new_events = 0;

    g_debug("prepare");
    /* go ahead and submit another read if there's room in the buffer
     * and no previous reads are outstanding
     */
    if (!rs->ov_pending) {
        if (rs->cur + rs->pending >= rs->buf_size) {
            if (rs->cur) {
                memmove(rs->buf, rs->buf + rs->cur, rs->pending);
                rs->cur = 0;
            }
        }
        count_to_read = rs->buf_size - rs->cur - rs->pending;
    }

    if (rs->ov_pending || count_to_read <= 0) {
            goto out;
    }

    /* submit the read */
    success = ReadFile(c->handle, rs->buf + rs->cur + rs->pending,
                       count_to_read, &count_read, &rs->ov);
    if (success) {
        rs->pending += count_read;
        rs->ov_pending = false;
    } else {
        if (GetLastError() == ERROR_IO_PENDING) {
            rs->ov_pending = true;
        } else {
            new_events |= G_IO_ERR;
        }
    }

out:
    /* don't block forever, iterate the main loop every once in a while */
    *timeout_ms = 500;
    /* if there's data in the read buffer, or another event is pending,
     * skip polling and issue user cb.
     */
    if (rs->pending) {
        new_events |= G_IO_IN;
    }
    c->pending_events |= new_events;
    return !!c->pending_events;
}

/*
 * Called by glib after an outstanding read request is completed.
 */
static gboolean ga_channel_check(GSource *source)
{
    GAWatch *watch = (GAWatch *)source;
    GAChannel *c = (GAChannel *)watch->channel;
    GAChannelReadState *rs = &c->rstate;
    DWORD count_read, error;
    BOOL success;

    GIOCondition new_events = 0;

    g_debug("check");

    /* failing this implies we issued a read that completed immediately,
     * yet no data was placed into the buffer (and thus we did not skip
     * polling). but since EOF is not obtainable until we retrieve an
     * overlapped result, it must be the case that there was data placed
     * into the buffer, or an error was generated by Readfile(). in either
     * case, we should've skipped the polling for this round.
     */
    g_assert(rs->ov_pending);

    success = GetOverlappedResult(c->handle, &rs->ov, &count_read, FALSE);
    if (success) {
        g_debug("thread: overlapped result, count_read: %d", (int)count_read);
        rs->pending += count_read;
        new_events |= G_IO_IN;
    } else {
        error = GetLastError();
        if (error == 0 || error == ERROR_HANDLE_EOF ||
            error == ERROR_NO_SYSTEM_RESOURCES ||
            error == ERROR_OPERATION_ABORTED) {
            /* note: On WinXP SP3 with rhel6ga virtio-win-1.1.16 vioser drivers,
             * ENSR seems to be synonymous with when we'd normally expect
             * ERROR_HANDLE_EOF. So treat it as such. Microsoft's
             * recommendation for ERROR_NO_SYSTEM_RESOURCES is to
             * retry the read, so this happens to work out anyway. On newer
             * virtio-win driver, this seems to be replaced with EOA, so
             * handle that in the same fashion.
             */
            new_events |= G_IO_HUP;
        } else if (error != ERROR_IO_INCOMPLETE) {
            g_critical("error retrieving overlapped result: %d", (int)error);
            new_events |= G_IO_ERR;
        }
    }

    if (new_events) {
        rs->ov_pending = 0;
    }
    c->pending_events |= new_events;

    return !!c->pending_events;
}

/*
 * Called by glib after either prepare or check routines signal readiness
 */
static gboolean ga_channel_dispatch(GSource *source, GSourceFunc unused,
                                    gpointer user_data)
{
    GAWatch *watch = (GAWatch *)source;
    GAChannel *c = (GAChannel *)watch->channel;
    GAChannelReadState *rs = &c->rstate;
    gboolean success;

    g_debug("dispatch");
    success = c->common.event_cb(watch->pollfd.revents, c->common.user_data);

    if (c->pending_events & G_IO_ERR) {
        g_critical("channel error, removing source");
        return false;
    }

    /* TODO: replace rs->pending with watch->revents */
    c->pending_events &= ~G_IO_HUP;
    if (!rs->pending) {
        c->pending_events &= ~G_IO_IN;
    } else {
        c->pending_events = 0;
    }
    return success;
}

static void ga_channel_finalize(GSource *source)
{
    g_debug("finalize");
}

GSourceFuncs ga_channel_watch_funcs = {
    ga_channel_prepare,
    ga_channel_check,
    ga_channel_dispatch,
    ga_channel_finalize
};

static GSource *ga_channel_create_watch(GAChannel *c)
{
    GSource *source = g_source_new(&ga_channel_watch_funcs, sizeof(GAWatch));
    GAWatch *watch = (GAWatch *)source;

    watch->channel = c;
    watch->pollfd.fd = (gintptr) c->rstate.ov.hEvent;
    g_source_add_poll(source, &watch->pollfd);

    return source;
}

/*
 * Socket mode: GIOChannel-based listen/accept/client helpers
 */

static gboolean ga_channel_socket_client_event(GIOChannel *channel,
                                               GIOCondition condition,
                                               gpointer data);
static gboolean ga_channel_socket_listen_accept(GIOChannel *channel,
                                                GIOCondition condition,
                                                gpointer data);

static void ga_channel_socket_listen_add(GAChannel *c, bool create)
{
    if (create) {
        c->common.listen_channel =
            g_io_channel_win32_new_socket(_get_osfhandle(c->listen_fd));
        g_assert(c->common.listen_channel);
    }
    g_io_add_watch(c->common.listen_channel, G_IO_IN,
                   ga_channel_socket_listen_accept, c);
}

static gboolean ga_channel_socket_client_close(GAChannel *c)
{
    /* Free the CRT fd wrapper while the SOCKET is still valid. */
    if (c->client_fd >= 0) {
        qemu_close_socket_osfhandle(c->client_fd);
        c->client_fd = -1;
    }
    ga_channel_common_client_close(&c->common);
    if (c->common.listen_channel) {
        ga_channel_socket_listen_add(c, false);
    }
    return false;
}

static gboolean ga_channel_socket_listen_accept(GIOChannel *channel,
                                                GIOCondition condition,
                                                gpointer data)
{
    GAChannel *c = data;
    int client_fd;
    GIOChannel *client_ch;
    bool accepted = false;

    client_fd = qemu_accept(c->listen_fd, NULL, NULL);
    if (client_fd < 0) {
        g_warning("error accepting connection: %s", strerror(errno));
        goto out;
    }

    /*
     * g_io_channel_win32_new_socket() makes the socket nonblocking via
     * WSAEventSelect.
     */
    client_ch = g_io_channel_win32_new_socket(_get_osfhandle(client_fd));
    g_assert(client_ch);

    if (ga_channel_common_client_add(&c->common, client_ch,
                                     ga_channel_socket_client_event, c)) {
        g_warning("error setting up connection");
        /*
         * Release the CRT fd wrapper while its SOCKET is still open - only
         * then qemu_close_socket_osfhandle() can detach the fd and let the
         * channel teardown perform the single closesocket().
         */
        qemu_close_socket_osfhandle(client_fd);
        ga_channel_common_gio_destroy(client_ch);
        goto out;
    }
    c->client_fd = client_fd;
    accepted = true;

out:
    /* only accept 1 connection at a time */
    return !accepted;
}

static gboolean ga_channel_socket_client_event(GIOChannel *channel,
                                               GIOCondition condition,
                                               gpointer data)
{
    GAChannel *c = data;

    g_assert(c);
    if (!c->common.event_cb(condition, c->common.user_data)) {
        return ga_channel_socket_client_close(c);
    }
    /*
     * A peer that sends data and disconnects at once is never reported:
     * GLib turns the coalesced FD_READ|FD_CLOSE into a plain G_IO_IN,
     * and Winsock records FD_CLOSE only once, so no later event follows.
     * Peek after each event to detect the disconnect.
     */
    if (c->client_fd >= 0) {
        char peek;
        ssize_t r = recv(c->client_fd, &peek, 1, MSG_PEEK);
        if (r == 0 || (r < 0 && errno != EAGAIN)) {
            return ga_channel_socket_client_close(c);
        }
    }
    return true;
}

/*
 * Handle mode: overlapped I/O read/write
 */

static GIOStatus ga_channel_handle_read(GAChannel *c, char *buf, size_t size,
                                        gsize *count)
{
    GAChannelReadState *rs = &c->rstate;
    GIOStatus status;
    size_t to_read = 0;

    if (c->pending_events & G_IO_ERR) {
        return G_IO_STATUS_ERROR;
    }

    *count = to_read = MIN(size, rs->pending);
    if (to_read) {
        memcpy(buf, rs->buf + rs->cur, to_read);
        rs->cur += to_read;
        rs->pending -= to_read;
        status = G_IO_STATUS_NORMAL;
    } else {
        status = G_IO_STATUS_AGAIN;
    }

    return status;
}

static GIOStatus ga_channel_handle_write(GAChannel *c, const char *buf,
                                         size_t size, size_t *count)
{
    GIOStatus status;
    OVERLAPPED ov = {0};
    BOOL ret;
    DWORD written;

    ov.hEvent = CreateEvent(NULL, FALSE, FALSE, NULL);
    ret = WriteFile(c->handle, buf, size, &written, &ov);
    if (!ret) {
        if (GetLastError() == ERROR_IO_PENDING) {
            /* write is pending */
            ret = GetOverlappedResult(c->handle, &ov, &written, TRUE);
            if (!ret) {
                if (!GetLastError()) {
                    status = G_IO_STATUS_AGAIN;
                } else {
                    status = G_IO_STATUS_ERROR;
                }
            } else {
                /* write is complete */
                status = G_IO_STATUS_NORMAL;
                *count = written;
            }
        } else {
            status = G_IO_STATUS_ERROR;
        }
    } else {
        /* write returned immediately */
        status = G_IO_STATUS_NORMAL;
        *count = written;
    }

    if (ov.hEvent) {
        CloseHandle(ov.hEvent);
        ov.hEvent = NULL;
    }
    return status;
}

GIOStatus ga_channel_read(GAChannel *c, char *buf, size_t size, gsize *count)
{
    if (c->common.method == GA_CHANNEL_VSOCK_LISTEN) {
        return ga_channel_common_read(&c->common, buf, size, count);
    }
    return ga_channel_handle_read(c, buf, size, count);
}

GIOStatus ga_channel_write_all(GAChannel *c, const char *buf, size_t size)
{
    GIOStatus status = G_IO_STATUS_NORMAL;
    size_t count = 0;

    if (c->common.method == GA_CHANNEL_VSOCK_LISTEN) {
        return ga_channel_common_write_all(&c->common, buf, size);
    }

    while (size) {
        status = ga_channel_handle_write(c, buf, size, &count);
        if (status == G_IO_STATUS_NORMAL) {
            size -= count;
            buf += count;
        } else if (status != G_IO_STATUS_AGAIN) {
            break;
        }
    }
    return status;
}

static gboolean ga_channel_open(GAChannel *c, GAChannelMethod method,
                                const gchar *path, Error **errp)
{
    COMMTIMEOUTS comTimeOut = {0};
    gchar newpath[MAXPATHLEN] = {0};
    comTimeOut.ReadIntervalTimeout = 1;

    c->common.method = method;

    switch (method) {
    case GA_CHANNEL_VIRTIO_SERIAL:
    case GA_CHANNEL_ISA_SERIAL:
        if (method == GA_CHANNEL_ISA_SERIAL) {
            snprintf(newpath, sizeof(newpath), "\\\\.\\%s", path);
        } else {
            g_strlcpy(newpath, path, sizeof(newpath));
        }

        c->handle = CreateFile(newpath, GENERIC_READ | GENERIC_WRITE, 0, NULL,
                               OPEN_EXISTING,
                               FILE_FLAG_NO_BUFFERING | FILE_FLAG_OVERLAPPED,
                               NULL);
        if (c->handle == INVALID_HANDLE_VALUE) {
            g_autofree gchar *emsg = g_win32_error_message(GetLastError());
            error_setg(errp, "error opening path %s: %s", newpath, emsg);
            c->handle = NULL;
            return false;
        }

        if (method == GA_CHANNEL_ISA_SERIAL
                && !SetCommTimeouts(c->handle, &comTimeOut)) {
            g_autofree gchar *emsg = g_win32_error_message(GetLastError());
            error_setg(errp, "error setting timeout for com port: %s", emsg);
            CloseHandle(c->handle);
            c->handle = NULL;
            return false;
        }
        return true;

#ifdef CONFIG_AF_VSOCK
    case GA_CHANNEL_VSOCK_LISTEN: {
        int fd = ga_channel_common_vsock_listen(path, errp);
        if (fd < 0) {
            return false;
        }

        c->listen_fd = fd;
        ga_channel_socket_listen_add(c, true);
        return true;
    }
#endif

    default:
        error_setg(errp, "unsupported communication method");
        return false;
    }
}

GAChannel *ga_channel_new(GAChannelMethod method, const gchar *path,
                          int listen_fd, GAChannelCallback cb, gpointer opaque)
{
    Error *err = NULL;
    GAChannel *c = g_new0(GAChannel, 1);

    /* listen_fd is for systemd socket activation; not applicable on Windows. */
    (void)listen_fd;
    c->listen_fd = -1;
    c->client_fd = -1;
    c->common.event_cb = cb;
    c->common.user_data = opaque;

    if (!ga_channel_open(c, method, path, &err)) {
        g_critical("%s", error_get_pretty(err));
        error_free(err);
        ga_channel_free(c);
        return NULL;
    }

    if (c->common.method != GA_CHANNEL_VSOCK_LISTEN) {
        SECURITY_ATTRIBUTES sec_attrs;

        sec_attrs.nLength = sizeof(SECURITY_ATTRIBUTES);
        sec_attrs.lpSecurityDescriptor = NULL;
        sec_attrs.bInheritHandle = false;

        c->rstate.buf_size = QGA_READ_COUNT_DEFAULT;
        c->rstate.buf = g_malloc(QGA_READ_COUNT_DEFAULT);
        c->rstate.ov.hEvent = CreateEvent(&sec_attrs, FALSE, FALSE, NULL);

        c->source = ga_channel_create_watch(c);
        g_source_attach(c->source, NULL);
    }

    return c;
}

void ga_channel_free(GAChannel *c)
{
    if (c->common.method == GA_CHANNEL_VSOCK_LISTEN) {
        /* Free the CRT fd wrappers before the GIOChannels close the SOCKETs. */
        if (c->listen_fd >= 0) {
            qemu_close_socket_osfhandle(c->listen_fd);
        }
        if (c->client_fd >= 0) {
            qemu_close_socket_osfhandle(c->client_fd);
        }
        ga_channel_common_free(&c->common);
        g_free(c);
        return;
    }

    /* Handle mode */
    if (c->source) {
        g_source_destroy(c->source);
    }
    if (c->rstate.ov.hEvent) {
        CloseHandle(c->rstate.ov.hEvent);
    }
    g_free(c->rstate.buf);
    g_free(c);
}
