#!/usr/bin/env python
#
# OpenBSD VM image
#
# Copyright 2017 Red Hat Inc.
#
# Authors:
#  Fam Zheng <famz@redhat.com>
#
# This code is licensed under the GPL version 2 or later.  See
# the COPYING file in the top-level directory.
#

import os
import sys
import subprocess
import time
import atexit
import tempfile
import basevm

class OpenBSDVM(basevm.BaseVM):
    name = "openbsd"
    BUILD_SCRIPT = """
        set -e;
        rm -rf /var/tmp/qemu-test.*
        cd $(mktemp -d /var/tmp/qemu-test.XXXXXX);
        tar -xf /dev/rsd1c;
        ./configure {configure_opts};
        gmake --output-sync -j{jobs} {verbose};
        # XXX: "gmake check" seems to always hang or fail
        #gmake --output-sync -j{jobs} check {verbose};
    """

    def _install_os(self, img):
        tmpdir = tempfile.mkdtemp()
        pxeboot = self._download_with_cache("https://fastly.cdn.openbsd.org/pub/OpenBSD/6.3/amd64/pxeboot",
                sha256sum="60029919798f48ea40ecb123adfed6217f099d5ed9cd1a6c7de5b544d7b7b0f6")
        bsd_rd = self._download_with_cache("https://fastly.cdn.openbsd.org/pub/OpenBSD/6.3/amd64/bsd.rd",
                sha256sum="1c0adb43a02ae3aee512bcf0829dac0ccb2e4d614b161049af7ce530e5da2dfc")
        install = self._download_with_cache("https://fastly.cdn.openbsd.org/pub/OpenBSD/6.3/amd64/install63.iso",
                sha256sum='ee775405dd7926975befbc3fef23de8c4b5a726c3b5075e4848fcd3a2a712ea8')
        subprocess.check_call(["qemu-img", "create", img, "32G"])
        subprocess.check_call(["cp", pxeboot, os.path.join(tmpdir, "auto_install")])
        subprocess.check_call(["cp", bsd_rd, os.path.join(tmpdir, "bsd")])

        self._gen_install_conf(tmpdir)
        try:
            self.start_http_server(tmpdir, ports=[80], sudo=True)
        except Exception:
            sys.stdout.write("Cannot open HTTP server on port 80. Maybe use sudo?\n")
            sys.exit(1)
        # BOOTP filename being auto_install makes sure OpenBSD installer
        # not prompt for "auto install mode"
        tftp_args = ",tftp=%s,bootfile=/auto_install" % tmpdir
        self.boot(img,
                  extra_args=["-boot", "once=n", "-no-reboot",
                              "-cdrom", install],
                  extra_usernet_args=tftp_args)
        self.wait()

    def _gen_install_conf(self, tmpdir):
        contents = """
System hostname = qemu-openbsd
Password for root = qemupass
Public ssh key for root = {pub_key}
Allow root ssh login = yes
Network interfaces = vio0
IPv4 address for vio0 = dhcp
Setup a user = qemu
Password for user = qemupass
Public ssh key for user = {pub_key}
What timezone are you in = US/Eastern
Server = fastly.cdn.openbsd.org
Use http = yes
Default IPv4 route = 10.0.2.2
Location of sets = cd0
Set name(s) = all
Continue without verification = yes
""".format(pub_key=basevm.SSH_PUB_KEY)
        with open(os.path.join(tmpdir, "install.conf"), "w") as f:
            f.write(contents)

    def build_image(self, img):

        self._install_os(img + ".tmp")

        self.boot(img + ".tmp")
        self.wait_ssh()

        self.ssh_root("usermod -G operator qemu")
        self.ssh_root("echo https://fastly.cdn.openbsd.org/pub/OpenBSD > /etc/installurl")
        for pkg in ["git", "gmake", "glib2", "bison", "sdl2"]:
            self.ssh_root("pkg_add " + pkg)
        self.ssh_root("ln -sf /usr/local/bin/python2.7 /usr/local/bin/python")
        self.ssh_root("ln -sf /usr/local/bin/python2.7-2to3 /usr/local/bin/2to3")
        self.ssh_root("ln -sf /usr/local/bin/python2.7-config /usr/local/bin/python-config")
        self.ssh_root("ln -sf /usr/local/bin/pydoc2.7 /usr/local/bin/pydoc")
        self.ssh_root("shutdown -p now")
        self.wait()

        subprocess.check_call(["mv", img + ".tmp", img])

if __name__ == "__main__":
    sys.exit(basevm.main(OpenBSDVM))
