# -*- Mode: makefile -*-
#
# Alpha specific tweaks

ALPHA_SRC=$(SRC_PATH)/tests/tcg/alpha
VPATH+=$(ALPHA_SRC)

ALPHA_TESTS=hello-alpha test-cond test-cmov test-ovf
TESTS+=$(ALPHA_TESTS)

test-cmov: EXTRA_CFLAGS=-DTEST_CMOV
test-cmov: test-cond.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $< -o $@ $(LDFLAGS)

run-test-cmov: test-cmov

# currently broken: executes a halt on sigreturn leading to being terminated by signal SIGILL (Illegal instruction)
run-signals: signals
	$(call skip-test, $<, "BROKEN")

run-plugin-signals-with-%: signals
	$(call skip-test, $<, "BROKEN")

# On Alpha Linux only supports 8k pages
EXTRA_RUNS+=run-test-mmap-8192
