.container_job_template:
  extends: .base_job_template
  stage: containers
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    DOCKERFILE: "$CI_PROJECT_DIR/tests/docker/dockerfiles/$NAME.docker"
    CACHE_REPO: "$CI_REGISTRY/qemu-project/qemu/qemu/$NAME-cache"
  before_script:
    - export TAG="$CI_REGISTRY_IMAGE/qemu/$NAME:$QEMU_CI_CONTAINER_TAG"
  script:
    - echo "TAG:$TAG"
    - /kaniko/executor
      --dockerfile "$DOCKERFILE"
      --destination "$TAG"
      --cache=true
      --cache-repo="$CACHE_REPO"
