amd64-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-amd64-cross

amd64-debian-user-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-all-test-cross

amd64-debian-legacy-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-legacy-test-cross

arm64-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-arm64-cross

armhf-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-armhf-cross

hexagon-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-hexagon-cross

loongarch-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-loongarch-cross

i686-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-i686-cross

mips64el-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-mips64el-cross

mipsel-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-mipsel-cross

ppc64el-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-ppc64el-cross

riscv64-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-riscv64-cross

s390x-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-s390x-cross

tricore-debian-cross-container:
  extends: .container_job_template
  stage: containers
  variables:
    NAME: debian-tricore-cross

xtensa-debian-cross-container:
  extends: .container_job_template
  variables:
    NAME: debian-xtensa-cross

win64-fedora-cross-container:
  extends: .container_job_template
  variables:
    NAME: fedora-win64-cross

wasm32-32bit-emsdk-cross-container:
  extends: .container_job_template
  variables:
    NAME: emsdk-wasm32-32bit-cross
    BUILD_ARGS: --build-arg TARGET_CPU=wasm32
    DOCKERFILE: emsdk-wasm-cross

wasm64-64bit-emsdk-cross-container:
  extends: .container_job_template
  variables:
    NAME: emsdk-wasm64-64bit-cross
    BUILD_ARGS: --build-arg TARGET_CPU=wasm64 --build-arg WASM64_MEMORY64=1
    DOCKERFILE: emsdk-wasm-cross

wasm64-32bit-emsdk-cross-container:
  extends: .container_job_template
  variables:
    NAME: emsdk-wasm64-32bit-cross
    BUILD_ARGS: --build-arg TARGET_CPU=wasm64 --build-arg WASM64_MEMORY64=2
    DOCKERFILE: emsdk-wasm-cross
