# -*- Mode: makefile -*-
#
# MIPS - included from tests/tcg/Makefile.target
#

MIPS_SRC=$(SRC_PATH)/tests/tcg/mips

# Set search path for all sources
VPATH 		+= $(MIPS_SRC)

ifneq ($(findstring 64,$(TARGET_NAME)),)
VPATH += $(MIPS_SRC)/user/isa/octeon

MIPS64_TESTS=octeon-insns

TESTS += $(MIPS64_TESTS)

octeon-insns: CFLAGS+=-mabi=64
run-octeon-insns: QEMU_OPTS+=-cpu Octeon68XX
endif

# hello-mips is 32 bit only
ifeq ($(findstring 64,$(TARGET_NAME)),)
MIPS_TESTS=hello-mips

TESTS += $(MIPS_TESTS)

hello-mips: CFLAGS+=-mno-abicalls -fno-PIC -fno-stack-protector -mabi=32
hello-mips: LDFLAGS+=-nostdlib
endif
